version: '3.8'
services:
  # PHP - Service
  app:
    build:
      context: .
      target: php
      args:
       - APP_ENV=${APP_ENV}

    container_name: app
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    environment:
      - APP_ENV=${APP_ENV}
      - CONTAINER_ROLE=app
      - JWT_SECRET=${JWT_SECRET}
      - APP_KEY=${APP_KEY}
    ports:
      - 8000:8000
    depends_on:
      - mariadb
      - redis
    volumes:
      - ./:/var/www
      - ./Docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini

    networks:
      - app-network

  # MariaDB - Service
  mariadb:
    image: mariadb
    container_name: mariadb
    restart: unless-stopped
    tty: true

    ports:
      - 3306:3306

    environment:
      MYSQL_DATABASE: laravel-app
      MYSQL_ROOT_PASSWORD: root

    volumes:
      - mariadbdata:/var/lib/mysql
      - ./Docker/mysql/my.cnf:/etc/mysql/my.cnf
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    networks:
      - app-network
  redis:
     image: redis:alpine
     container_name: redis
     command: redis-server --appendonly yes
     ports:
        - 6379:6379
     volumes:
        - ./redis:/data
     networks:
        - app-network

# Volumes
volumes:
  mariadbdata:
    driver: local

# Networks
networks:
  app-network:
    driver: bridge
